name: spamit
description: An Instagram-like social media app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_animate: ^4.2.0
  cached_network_image: ^3.2.3
  flutter_native_splash: ^2.3.1
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
    - assets/placeholder.jpg
    - assets/profile_placeholder.jpg
    - assets/groups.json
